version: "3"

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure

services:
  gateway:
    build:
      context: ../../production
      dockerfile: ../deploy/docker/gateway/Dockerfile
    restart: always
    hostname: gateway
    env_file:
      - ../../config/.env
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    links:
     - example

  example:
    build:
      context: ../../production
      dockerfile: ../deploy/docker/example/Dockerfile
    restart: always
    hostname: example
    env_file:
      - ../../config/.env
    networks:
      - backend
    # links:
    #  - db

  # Uncomment to enable MongoDB
  # db:
  #   image: "mongo"
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  #     MONGO_USER: ${MONGO_USER}
  #     MONGO_PASSWORD: ${MONGO_PASSWORD}
  #     TZ: "Europe/Warsaw"
  #   volumes:
  #     - "./db/data/db-files:/data/db"
  #     - "./db/init/:/docker-entrypoint-initdb.d/"
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - backend

  # Uncomment to enable redis
  # redis:
  #   image: redis
  #   restart: always
  #   hostname: redis
  #   networks:
  #     - backend
  #   env_file:
  #     - ../../config/.env

  # Uncomment to enable RabbitMQ
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   restart: always
  #   hostname: rabbitmq
  #   networks:
  #     - frontend
  #     - backend
  #   env_file:
  #     - ../../config/.env
  #   # Uncomment to initialize RabbitMQ with predefined configuration
  #   # volumes:
  #   #  - './configs/rabbitmq-init.json:/tmp/rabbitmq-init.json'
  #   # environment:
  #   #  - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbitmq-init.json"

  #   # Uncomment to expose RabbitMQ Management service port
  #   # ports:
  #   #  - "15672:15672"
